x-default-logging: &logging
  driver: "json-file"
  options:
    max-size: "5m"
    max-file: "2"
    tag: "{{.Name}}"
    
services:
  postgresql:
    image: docker.io/library/postgres:16-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    volumes:
      - database:/var/lib/postgresql/data
      - /mnt/h/PGBackup:/mnt/backup
    environment:
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_USER: ${PG_USER:-authentik}
      POSTGRES_DB: ${PG_DB:-authentik}
    env_file:
      - stack.env
    networks:
      - non-routable
    logging: *logging
    deploy:
      resources:
        limits:
          memory: 100m
    
  redis:
    image: docker.io/library/redis:alpine
    command: --save 60 1 --loglevel warning
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    volumes:
      - redis:/data
    networks:
      - non-routable
    logging: *logging
    deploy:
      resources:
        limits:
          memory: 100m
    
  server:
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2024.12.2}
    restart: unless-stopped
    command: server
    environment:
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
    volumes:
      - authentik_server:/media
      - authentik_server:/templates
    env_file:
      - stack.env
    deploy:
      resources:
        limits:
          memory: 300m

    depends_on:
      postgresql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - routable
      - non-routable
    logging: *logging
    
  worker:
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2024.12.2}
    restart: unless-stopped
    command: worker
    environment:
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - authentik_server:/media
      - authentik_server:/certs
      - authentik_server:/templates
    env_file:
      - stack.env
    networks:
      - routable
      - non-routable
    depends_on:
      postgresql:
        condition: service_healthy
      redis:
        condition: service_healthy
    logging: *logging
    deploy:
      resources:
        limits:
          memory: 300m

volumes:
  database:
    name: authentik_database
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/pradh33p/authentik_database
  redis:
    name: authentik_redis
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /mnt/g/docker/volumes/authentik/redis
  authentik_server:
    name: authentik_server
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /mnt/g/docker/volumes/authentik/server

networks:
  routable:
    external: true
  non-routable:
    external: true
