services:
  cloudflared:
    image: cloudflare/cloudflared:2024.12.2
    container_name: cloudflared
    restart: always
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=$Token
    volumes:
      - ./cloudflared:/etc/cloudflared
    networks:
      - routable

networks:
  routable:
   external: true
