x-default-logging: &logging
  driver: "json-file"
  options:
    max-size: "5m"
    max-file: "2"
    tag: "{{.Name}}"
services:
  portainer:
    image: portainer/portainer-ce:2.21.0
    container_name: portainer
    hostname: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_volume:/data
    networks:
      - routable
      - non-routable
    restart: always
    logging: *logging
