services:
  uptime_kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime_kuma
    hostname: uptime_kuma
    restart: always
    volumes:
      - uptime-kuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - routable
      
volumes:
  uptime-kuma:
    name: uptime_kuma_volume
    driver: local
    driver_opts:
       o: bind
       type: none
       device: /mnt/g/docker/volumes/uptime_kuma

networks:
  routable:
    external: true
